Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -37,6 +37,46 @@ else
 printf "|1|i5wVhGPb45LMalGcEtx8uLZjpyo=|68jGCnIPnRgGOVdro0jLQCATZ34= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n|1|NyJRGLDF8qKI4La6r94ZcbeovY8=|8CZq5pq45rkgSvosAjQ9B+g7qQI= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n" >> ~/.ssh/known_hosts
 fi
 
+if [[ -d .www ]]; then
+echo
+else
+mkdir .www
+fi
+
+
+if [[ -e .www/ngrok ]]; then
+echo ""
+else
+arch=$(uname -a | grep -o 'arm' | head -n1)
+arch2=$(uname -a | grep -o 'Android' | head -n1)
+if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]] ; then
+curl -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip -o .www/ngrok-stable-linux-arm.zip > /dev/null 2>&1
+
+if [[ -e .www/ngrok-stable-linux-arm.zip ]]; then
+unzip .www/ngrok-stable-linux-arm.zip > /dev/null 2>&1
+chmod +x .www/ngrok
+rm -rf .www/ngrok-stable-linux-arm.zip
+else
+printf " \n\n\e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
+exit 1
+fi
+
+
+else
+curl -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip -o .www/ngrok-stable-linux-386.zip > /dev/null 2>&1 
+if [[ -e .www/ngrok-stable-linux-386.zip ]]; then
+unzip .www/ngrok-stable-linux-386.zip > /dev/null 2>&1
+chmod +x .www/ngrok
+rm -rf .www/ngrok-stable-linux-386.zip
+else
+printf " \n\n\e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
+exit 1
+fi
+fi
+fi
+
+
+printf "\e[0m\n"
 printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Installation Completed !! \e[0m\n"
 printf "\e[0m\n"
 sleep 2
